# Exclude Jinja2 template files and template directories
exclude = [
    "*.j2",
]

[lint]
preview = true

select = [
    # flake8
    "A", "ARG", "B", "BLE", "C4", "PIE", "RET", "SIM", "S",
    "E", # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "N",  # pep8-nameing
    "PLE", # pylint
    "PTH", # pathlib
    "RUF", # ruff-specific rules
    "UP", # pyupgrade
    "W", # pycodestyle warnings
]

ignore = [
    "ARG002", # Unused parameter
    "B018", # Useless Expression not assigned to variable
    "E501", # Line too long
    "N818", # Exception name should be named with an Error suffix
    "B009", # Do not call getattr with a constant attribute value.
    "PLR2004", # Magic Value Used in comparison
    "RUF012",  # Mutable class attributes should be annotated with typing.ClassVar
    "E203",    # Whitespace before ':'
    "PLC1901", # can be simplified to `not value_ctx` as an empty string is falsey
    "RUF100", # Unused noqa, will handle with automated checks
    "S701", # Require auto_escape for jinja templates

]

[lint.per-file-ignores]
"tests/*" = [
    "S101",
]
